context:
  version: "0.2.2"

package:
  name: modctl
  version: ${{ version }}

source:
  url: https://github.com/modelpack/modctl/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 339f9db84db5c6e21168489561e4b09f5b57b77a784637afdc2939cae58eef60

build:
  number: 0
  script:
    interpreter: nu
    content:
      - let prefix = $env.LIBRARY_PREFIX? | default $env.PREFIX
      # build main app and generate license data
      - let build_time = date now | format date "%Y-%m-%dT%H:%M:%SZ"
      - let short_commit_hash = (http get https://api.github.com/repos/modelpack/modctl/commits/v${{ version }}).sha | str substring 0..6
      - ^go build
        -o ($prefix)/bin/
        -v
        -ldflags=$'-s -w -X github.com/modelpack/modctl/pkg/version.BuildTime=($build_time) -X github.com/modelpack/modctl/pkg/version.GitCommit=($short_commit_hash) -X github.com/modelpack/modctl/pkg/version.GitVersion=${{ version }}'
        -trimpath
        .
      - ^go-licenses save . --save_path=library_licenses
      # generate shell completions
      - if: build_platform == host_platform
        then:
          - ^modctl completion bash | save --force ($prefix)/share/bash-completion/completions/modctl
          - ^modctl completion fish | save --force ($prefix)/share/fish/vendor_completions.d/modctl.fish
          - ^modctl completion zsh  | save --force ($prefix)/share/zsh/site-functions/_modctl
  skip:
    # Windows is currently unsupported, cf. https://github.com/modelpack/modctl/issues/472
    - win

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses
    - nushell

tests:
  - script:
      - modctl --help
      - modctl version
  - package_contents:
      bin:
        - modctl
      files:
        - if: unix
          then:
            - share/bash-completion/completions/modctl
            - share/fish/vendor_completions.d/modctl.fish
            - share/zsh/site-functions/_modctl
        - if: win
          then:
            - Library/share/bash-completion/completions/modctl
            - Library/share/fish/vendor_completions.d/modctl.fish
            - Library/share/zsh/site-functions/_modctl
      strict: true

about:
  summary: A CLI tool for managing OCI model artifacts bundled based on the ModelPack specification
  description: |
    Modctl is a user-friendly CLI tool for managing OCI model artifacts, which are
    bundled based on the ModelPack Model Specification. It offers commands such as
    build, pull, push, and more, making it easy to interact with AI/ML model registries.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  homepage: https://modelpack.org/
  documentation: https://github.com/modelpack/model-spec/tree/main/docs
  repository: https://github.com/modelpack/modctl

extra:
  recipe-maintainers:
    - salim-b
